name: Debug

on:
  workflow_dispatch:
  repository_dispatch:

jobs:
  build:

    if: github.actor == github.repository_owner
    runs-on: ubuntu-latest

    steps:
          
    - uses: actions/checkout@main
        
    - name: Setup interactive debug session
      # 调试
      uses: csexton/debugger-action@master
      env: 
        CONF: ${{ secrets.CONF }}
      
    - name: Run
      uses: coactions/setup-xvfb@main
      with:
        run: |
          dotnet run
          echo ${CONF}
      env: 
        CONF: ${{ secrets.CONF }}
